### ISSUE TITLE
E-mail администратора

### ISSUE THREAD

**Issue by sashabeep** [Serg28/tsvshop#2]
Необходимо ввести поле e-mail администратора магазина, на который будут приходить заказы. И чтобы в это поле можно было вписать несколько адресов в том числе. А то обратный адрес есть, а адреса администратора нет.

Сейчас берется обратный адрес e-mail из системных настроек. Это неправильно, потому что там вообще обычно указан адрес типа no-reply@domain.tld Администрированием сайта и заказами часто занимаются разные люди.

К слову, уведомления о заказах пока что мне не приходят вообще

**Comment by Serg28** [comment]
Будет исправлено в версии 5.4
