### ISSUE TITLE
Опечатка в cart.inc.php, которая не отображает форму checkout.

### ISSUE THREAD

**Issue by thalegion** [Serg28/tsvshop#5]
Добрый день. Наткнулся на опечатку.
Находится она в файле /include/cart.inc.php:956. Из-за неё вызов формы checkout по-умолчанию возвращает 1.
![image](https://user-images.githubusercontent.com/16190128/36542033-c035d006-17f0-11e8-8f13-6dc30b34aa78.png)

**Comment by Serg28** [comment]
Спасибо, внес правку
